---
driver:
  name: docker
  hostname: ceilometer.ci.local
  use_sudo: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  log_level: error
  formula: ceilometer
  grains:
    noservices: True
  dependencies:
    - name: linux
      repo: git
      source: https://github.com/salt-formulas/salt-formula-linux
  state_top:
    base:
      "*":
        - linux.system
        - ceilometer
  pillars:
    top.sls:
      base:
        "*":
          - linux_repo_openstack
          - ceilometer
          - release
  pillars-from-files:
    linux_repo_openstack.sls: tests/pillar/repo_mcp_openstack_<%= ENV['OS_VERSION'] || 'pike' %>.sls

verifier:
  name: inspec
  sudo: true

platforms:
  - name: <%=ENV['PLATFORM'] ||  'saltstack-ubuntu-xenial-salt-stable' %>
    driver_config:
      image: <%=ENV['PLATFORM'] || 'epcim/salt-formulas:saltstack-ubuntu-xenial-salt-stable'%>
      platform: ubuntu

suites:

  - name: agent_cluster
    provisioner:
      pillars-from-files:
        ceilometer.sls: tests/pillar/agent_cluster.sls
      pillars:
        release.sls:
          ceilometer:
            agent:
              version: <%= ENV['OS_VERSION'] || 'pike' %>

  - name: agent_single
    provisioner:
      pillars-from-files:
        ceilometer.sls: tests/pillar/agent_single.sls
      pillars:
        release.sls:
          ceilometer:
            agent:
              version: <%= ENV['OS_VERSION'] || 'pike' %>

  - name: server_cluster
    provisioner:
      pillars-from-files:
        ceilometer.sls: tests/pillar/server_cluster.sls
      pillars:
        release.sls:
          ceilometer:
            server:
              version: <%= ENV['OS_VERSION'] || 'pike' %>

  - name: server_gnocchi_cluster
    provisioner:
      pillars-from-files:
        ceilometer.sls: tests/pillar/server_gnocchi_cluster.sls
      pillars:
        release.sls:
          ceilometer:
            server:
              version: <%= ENV['OS_VERSION'] || 'pike' %>

  - name: server_single
    provisioner:
      pillars-from-files:
        ceilometer.sls: tests/pillar/server_single.sls
      pillars:
        release.sls:
          ceilometer:
            server:
              version: <%= ENV['OS_VERSION'] || 'pike' %>

  - name: server_cluster_ssl
    provisioner:
      pillars-from-files:
        ceilometer.sls: tests/pillar/server_cluster.sls
      pillars:
        release.sls:
          ceilometer:
            server:
              version: <%= ENV['OS_VERSION'] || 'pike' %>
        ssl.sls:
          ceilometer:
            server:
              identity:
                protocol: https
              message_queue:
                port: 5671
                ssl:
                  enabled: True
        top.sls:
          base:
            "*":
              - linux_repo_openstack
              - ceilometer
              - release
              - ssl

  - name: server_gnocchi_cluster_ssl
    provisioner:
      pillars-from-files:
        ceilometer.sls: tests/pillar/server_gnocchi_cluster.sls
      pillars:
        release.sls:
          ceilometer:
            server:
              version: <%= ENV['OS_VERSION'] || 'pike' %>
        ssl.sls:
          ceilometer:
            server:
              identity:
                protocol: https
              message_queue:
                port: 5671
                ssl:
                  enabled: True
        top.sls:
          base:
            "*":
              - linux_repo_openstack
              - ceilometer
              - release
              - ssl

  - name: agent_cluster_ssl
    provisioner:
      pillars-from-files:
        ceilometer.sls: tests/pillar/agent_cluster.sls
      pillars:
        release.sls:
          ceilometer:
            agent:
              version: <%= ENV['OS_VERSION'] || 'pike' %>
        ssl.sls:
          ceilometer:
            agent:
              identity:
                protocol: https
              message_queue:
                port: 5671
                ssl:
                  enabled: True
        top.sls:
          base:
            "*":
              - linux_repo_openstack
              - ceilometer
              - release
              - ssl

# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
